[package]
name = "app-boilerplate-rust"
version = "1.0.0"
authors = ["yhql", "agrojean-ledger"]
edition = "2021"

[dependencies]
nanos_sdk = { git = "https://github.com/LedgerHQ/ledger-nanos-sdk.git" }
nanos_ui = { git = "https://github.com/LedgerHQ/ledger-nanos-ui.git" }
include_gif = { git = "https://github.com/LedgerHQ/sdk_include_gif" }
numtoa = "0.2.4"

[profile.release]
opt-level = 'z'
lto = true

[features]
pending_review_screen = ["nanos_sdk/pending_review_screen"]

[package.metadata.ledger]
curve = ["secp256k1"]
flags = "0"
path = [""]

[package.metadata.ledger.nanos]
icon = "crab.gif"

[package.metadata.ledger.nanox]
icon = "crab_14x14.gif"

[package.metadata.ledger.nanosplus]
icon = "crab_14x14.gif"