[package]
name = "app-boilerplate-rust"
version = "1.0.0"
authors = ["yhql", "agrojean-ledger"]
edition = "2021"

[dependencies]
ledger_device_sdk = "1.0.0"
ledger_device_ui_sdk = "1.1.0"
ledger_secure_sdk_sys = "1.0.0"
include_gif = "1.0.0"
numtoa = "0.2.4"

[profile.release]
opt-level = 'z'
lto = true

[features]
pending_review_screen = ["ledger_device_sdk/pending_review_screen"]

[package.metadata.ledger]
curve = ["secp256k1"]
flags = "0"
path = [""]

[package.metadata.ledger.nanos]
icon = "crab.gif"

[package.metadata.ledger.nanox]
icon = "crab_14x14.gif"

[package.metadata.ledger.nanosplus]
icon = "crab_14x14.gif"
