name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install thumbv6 target
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        target: thumbv6m-none-eabi 
    - name: Cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build 
