name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
    inputs: 
      name: 
        description: 'Manually triggered'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name : Build
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-dev-tools:latest
    strategy:
      matrix:
        target: ["nanos", "nanox", "nanosplus"]
    steps:
    - name: Clone
      uses: actions/checkout@v3
    - name: Build app
      run: cargo ledger build ${{ matrix.target }}
  
  clippy_fmt:
    name: Run static analysis and formatting check
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-dev-tools:latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
      - name: Cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
